"use strict";
exports.__esModule = true;
require("./function/1_remove_duplicates_in_array");
require("./function/2_remove_duplicates_in_an_array_of_objects");
require("./function/3_iterate_array_iterates_with_index");
require("./function/4_separate_strings_by_number_of_characters");
require("./function/5_separate_strings_by_the_same_character");
require("./function/6_iterate_properties_in_an_object");
require("./type_definition/1_1_functions_with_different_return_types_in_different_cases");
require("./function/7_key_value_array_to_object_conversion");
require("./syntax/1_1_splitting_objects");
require("./function/9_");
