import "./function/1_remove_duplicates_in_array"
import "./function/2_remove_duplicates_in_an_array_of_objects"
import "./function/3_iterate_array_iterates_with_index"
import "./function/4_separate_strings_by_number_of_characters"
import "./function/5_separate_strings_by_the_same_character"
import "./function/6_iterate_properties_in_an_object"
import "./type_definition/1_1_functions_with_different_return_types_in_different_cases"
import "./function/7_key_value_array_to_object_conversion"